version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/task_manager 
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "4173:4173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
    restart: always

  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database_backup/task_db_backup.sql:/docker-entrypoint-initdb.d/task_db_backup.sql
volumes:
  postgres_data: