###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "1@2.com",
    "password": "admin"
}

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "test",
    "email": "1@2.com",
    "password": "admin"
}