###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "shantanugupta0412@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "name": "test",
    "email": "1@2.com",
    "password": "admin"
}

###
POST http://localhost:5000/tasks/add
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic2hhbnRhbnVndXB0YTA0MTJAZ21haWwuY29tIiwiaWF0IjoxNzQwOTM5NjQ5LCJleHAiOjE3NDA5NDMyNDl9.jScmrbEQc9yIxDJEtA83SQk5ig3Up1qSJdu5bzL9wfQ

{
    "title": "test",
    "description": "Testing the API endpint",
    "name": "Shantanu"
}

###
POST http://localhost:5000/tasks/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic2hhbnRhbnVndXB0YTA0MTJAZ21haWwuY29tIiwiaWF0IjoxNzQwOTM5NjQ5LCJleHAiOjE3NDA5NDMyNDl9.jScmrbEQc9yIxDJEtA83SQk5ig3Up1qSJdu5bzL9wfQ

{
    "title": "test",
    "status": "In Progress"
}

###
GET  http://localhost:5000/tasks/fetch
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic2hhbnRhbnVndXB0YTA0MTJAZ21haWwuY29tIiwiaWF0IjoxNzQwOTM5NjQ5LCJleHAiOjE3NDA5NDMyNDl9.jScmrbEQc9yIxDJEtA83SQk5ig3Up1qSJdu5bzL9wfQ

###
DELETE http://localhost:5000/tasks/delete
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoic2hhbnRhbnVndXB0YTA0MTJAZ21haWwuY29tIiwiaWF0IjoxNzQwOTM5NjQ5LCJleHAiOjE3NDA5NDMyNDl9.jScmrbEQc9yIxDJEtA83SQk5ig3Up1qSJdu5bzL9wfQ

{
    "title": "test"
}